"""
forever - generated by ScratchPy Studio 1.0.2.

This file is written automatically from the blocks in the
'forever' tab.  Editing it by hand is fine, but the next time
you press the green flag your changes will be replaced.
"""

import time

# ---- variables ----
score = 0
name = ""
things = []

def main():
    """Everything under the green flag."""
    while True:
        time.sleep(0.2)


if __name__ == "__main__":
    main()
