"""
helper - generated by ScratchPy Studio 1.0.

This file is written automatically from the blocks in the
'helper' tab.  Editing it by hand is fine, but the next time
you press the green flag your changes will be replaced.
"""

# ---- variables ----
score = 0
name = ""
things = []

def main():
    """Everything under the green flag."""
    pass


if __name__ == "__main__":
    main()
