"""
runtest - generated by ScratchPy Studio 1.2.0.

This file is written automatically from the blocks in the
'runtest' tab.  Editing it by hand is fine, but the next time
you press the green flag your changes will be replaced.
"""

def ask(prompt):
    """Show a question and wait for the answer (like Scratch's ask block)."""
    try:
        return input(str(prompt) + " ")
    except EOFError:
        return ""

# ---- variables ----
score = 0
name = ""
things = []

def main():
    """Everything under the green flag."""
    global score, name
    print("counting:")
    for _ in range(int(3)):
        score = score + 2
        print(f"score is {score}")
    name = ask("Who are you?")
    print(f"bye {name}")


if __name__ == "__main__":
    main()
