"""
webtest - generated by ScratchPy Studio 1.1.0.

This file is written automatically from the blocks in the
'webtest' tab.  Editing it by hand is fine, but the next time
you press the green flag your changes will be replaced.
"""

import json
import urllib.error
import urllib.parse
import urllib.request

WEB_HEADERS = {"User-Agent": "ScratchPy Studio"}
web_last = {"status": 0, "reason": "", "url": ""}


def web_header(name, value):
    """Send this header with every request from now on. API keys go here."""
    WEB_HEADERS[str(name)] = str(value)


def web_send(method, url, body=None, data=None, form=None, timeout=30):
    """Send any kind of web request and give back the reply as text."""
    address = str(url)
    if not address.lower().startswith(("http://", "https://")):
        raise ValueError("only http:// and https:// addresses work: " + address)
    headers = dict(WEB_HEADERS)
    payload = None
    if data is not None:
        payload = json.dumps(data).encode("utf-8")
        headers.setdefault("Content-Type", "application/json")
    elif form is not None:
        payload = urllib.parse.urlencode(form).encode("utf-8")
        headers.setdefault("Content-Type", "application/x-www-form-urlencoded")
    elif body is not None:
        payload = str(body).encode("utf-8")
    question = urllib.request.Request(address, data=payload, headers=headers,
                                      method=str(method).upper())
    try:
        with urllib.request.urlopen(question, timeout=timeout) as reply:
            web_last.update(status=reply.status, reason=reply.reason,
                            url=reply.url)
            charset = reply.headers.get_content_charset() or "utf-8"
            return reply.read().decode(charset, "replace")
    except urllib.error.HTTPError as problem:
        # 404, 500 and friends still have a body worth reading
        web_last.update(status=problem.code, reason=str(problem.reason),
                        url=address)
        charset = problem.headers.get_content_charset() or "utf-8"
        return problem.read().decode(charset, "replace")
    except urllib.error.URLError as problem:
        web_last.update(status=0, reason=str(problem.reason), url=address)
        raise


def web_get(url, timeout=30):
    """The text of a web page or an API answer."""
    return web_send("GET", url, timeout=timeout)


def web_json(url, timeout=30):
    """Fetch an API and turn its answer into records and lists."""
    return json.loads(web_get(url, timeout) or "null")


def web_status(url, timeout=30):
    """200 means it worked, 404 means it is missing, 0 means no answer."""
    try:
        web_send("GET", url, timeout=timeout)
    except Exception:
        return 0
    return web_last["status"]


def web_download(url, path, timeout=60):
    """Save whatever is at a web address into a file."""
    address = str(url)
    if not address.lower().startswith(("http://", "https://")):
        raise ValueError("only http:// and https:// addresses work: " + address)
    question = urllib.request.Request(address, headers=dict(WEB_HEADERS))
    with urllib.request.urlopen(question, timeout=timeout) as reply:
        web_last.update(status=reply.status, reason=reply.reason, url=reply.url)
        with open(path, "wb") as out:
            out.write(reply.read())
    return path


def web_address(base, values):
    """Add ?name=value pieces to a web address, spelled out safely."""
    query = urllib.parse.urlencode(values or {})
    if not query:
        return str(base)
    return str(base) + ("&" if "?" in str(base) else "?") + query

# ---- variables ----
score = 0
name = ""
things = []

def main():
    """Everything under the green flag."""
    web_header("X-Test", "from-blocks")
    print(web_get("http://127.0.0.1:59677/"))
    print(web_status("http://127.0.0.1:59677/missing"))
    print(web_send("POST", "http://127.0.0.1:59677/", data={'from': 'a block'}))


if __name__ == "__main__":
    main()
